version: '3.9'

services:
  postgres_db:
    image: 'postgres:latest'
    container_name: todo-postgres-db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: todo-db
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password

volumes:
  db_data:
